# `try-catch` block

- The `try` block contains the code that might throw an exception.
- If an exception is thrown, the `catch` block is executed.
- The `catch` block contains code to handle the exception.
- The *exception type* in the catch argument specifies the type of exception the block should handle.
- `try` should be followed by `catch` or `finally` or both

```java
try {
    // Some code that might throw an exception
} catch (Exception ex) {
    // Code to handle the exception
}
```
> `catch (Exception e)`: `Exception` is the superclass and will catches ***any*** exceptions.

> The `ex` variable is implicitly `final`, we can not reassign it.

### Multiple exceptions using a single `catch` blocks

- We can use a single catch block with multiple exceptions separed by `|` operator.

```java
try {
    // business logic
} catch (StringIndexOutOfBoundsException | ArrayIndexOutOfBoundsException  ex) {
    // catch multiple exceptions with the use of the operator |
} catch (Exception ex) {
    // default catch block
}
```
> Specific exceptions must be placed before more generics exceptions

# `finally` block

- `finally` block is a optional block used to ensure that some code will always be executed.
- This is useful to perform cleanup tasks.

```java
try {
    // Some code that might throw an exception
} catch (Exception ex) {
    // Code to handle the exception
} finally {
    // code that will always be executed
}
```

# `try` with resources statement (Java 7)

`try` with resources statement allow to close automatically any object implement **`AutoCloseable`** so we don't need to close manually inside `try` and `finally` block.

```java
try (Scanner scanner = new Scanner(System.in)) {
    // Some code that might throw an exception
} catch (Exception ex) {
    // Code to handle the exception
} 
```

> with *try-with-resources*, `catch` and `finally` block are optional.

# The Exception Hierarchy

- `catch` accept as argument only subclasses of `Throwable`witch include `Error` and `Exception` subclasses.
- Common `Throwable` methods:
  - z
- Common `Error` Exceptions:
  - z
  > Those errors can not be handled becaus they can not reach the `catch` block

> Use those method with a logger in production environment.

# Checked Exceptions

- *Checked exceptions* are exceptions forced by the compiler to be handled by the developper. Example: `IOException`, `SQLException`, `FileNotFoundException`.
- Checked exception are those that do **not** inherit from `java.lang.RuntimeException`.
- The compiler verifies that these exceptions are either caught or mentioned in the method's throws clause.

###  Handling Checked Exception

- For Example, the class `FileReader` has a `throws` clause in its constructor. 

    ```java
    // java.io.BufferReader
    public FileReader(String fileName) throws FileNotFoundException
    ```

- It forces us to handle the `FileNotFoundException` with a try-catch statement.
    ```java
    public void readFile() {
        try {
            FileReader fileReader = new FileReader("/Users/eazybytes/Desktop/story.txt");
        } catch (FileNotFoundException ex){
            ex.printStackTrace();
        }
    }
    ```

- Alternatively, we can add a `throws` clause to pass the exception up to the caller:
    ```java
    public void readFile() throws FileNotFoundException {
        FileReader fileReader = new FileReader("/Users/eazybytes/Desktop/story.txt");
    }
    ```
    > We are passing the responsability to handle the Exception to the caller of the method.

    > For best practice, we should handle the exception as soon possible.

# Unchecked Exceptions

- Unchecked exceptions are exceptions that the compiler does not require the programmer to handle. Example: `NullPointerException`, `ArrayIndexOutOfBoundsException`, `ArithmeticException`.
- All exceptions that inherit from `java.lang.RuntimeException` are unchecked exception.

###  Handling Unchecked Exception
Even this code compile, it will throw an exception at runtime, and should be handled with a `try-catch` statement.
```java
int[] numbers = {1, 2, 3};

// This line will throw an ArrayIndexOutOfBoundsException
int number = numbers[5];

System.out.println(number);
```

# `throws` keyword (plurial)

- `throws` keyword is utilized in the method signature to indicate that the method may throw certain exceptions.
- It is used to communicate to the caller that our method has potential exceptions, and need to be handled.
- It helps us to be aware the method we are calling has potential failures and needs to be handled.

```java
public double divide (String num1, String num2) throws
        NumberFormatException, ArithmeticException {
    int n1 = Integer.parseInt(num1);
    int n2 = Integer.parseInt(num2);
    return n1/n2;
}
```

```java
Division division = new Division();
try{
    double ouput = division.divide("4", "2");
    System.out.println(ouput);
} catch (NumberFormatException | ArithmeticException ex) {
    System.out.println("Invalid data provided. Please provide valid numbers and try again..");
}
```

# `throw` keyword (singular)

- `throw` keyword is used to explicitly throw an exception.
- It is mainly used to throw a **custom** exception

```java
if(num2.equals(0)) {
    throw new ArithmeticException("Division by zero");
}
```

> `throw` must be followed by an instance of the `Throwable` class

- If we `throw` a **checked** exception, we must also add the exception with the `throws` keyword in the method signature.
    ```java
    public static void main(String[] args) throws FileNotFoundException {
        throw new FileNotFoundException();
    }
    ```
    > `FileNotFoundException` is a **checked** expression, so we must add the `throws` clause.

# Exception Propagation

- When an exception is thrown from a method and is not caught within that method, it is propagated to the calling method.
  - This process continues until either the exception is caught by a catch block,
  - or it reaches the top-level method (main method), where it is handled by the default exception handler.
  
> The stack trace will show the sequence of method calls from where the exception was thrown to where it was caught.

# Nested `try` block

Nested try block allow to handle exceptions that may occur within a specific block, while still being able to handle exceptions that occur in the outer block.

```java
try {
    statement1;
    statement2;
    try {
        statement3;
    } catch (Exception e) {
        // handle exception
    } 
} catch (Exception e) {
    // handle exception
} 
```

# Custom Exception

- There are situations where it's necessary to add custom exceptions to complement standard exceptions.
- Benefits of using custom exceptions:
  1. Handle exceptions that are unique to the specific business logic.
  2. Help other developpers to pinpoint the exact cause of the problem.
  3. Catch and handle specific subsets of existing Java exceptions in a more targeted manner.
- to create a custon exception:
  - For ***checked*** exception: Our exception **must** extends the class `Exception` (not its subclass `RuntimeException`)
  - For ***unchecked*** Exception: Our exception **must** extends the class `RuntimeException`

### Example with *checked* exception

```java
public static void main(String[] args) throws InvalidAgeException {
    // ..
    if(age<0 || age>100) {
        throw new InvalidAgeException("Invalid age details entered. Please enter a age between 0-100");
    }
}
```
```java
public class InvalidAgeException extends Exception {
    public InvalidAgeException() {
        super();
    }
    public InvalidAgeException(String message) {
        super(message);
    }
}
```